load("//tools:defs.bzl", "bzl_library")

package(licenses = ["notice"])

bzl_library(
    name = "defs_bzl",
    srcs = ["defs.bzl"],
    visibility = [
        "//test/packetimpact/runner:__pkg__",
        "//test/runner:__pkg__",
        "//test/runtimes:__pkg__",
        "//tools/vm:__pkg__",
        "//website:__pkg__",
    ],
)
